# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    env:
      OMP_NUM_THREADS: 1
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: 3.8
          - os: ubuntu-latest
            python-version: 3.9
          # TODO: https://github.com/r9y9/nnmnkwii/issues/124
          # - os: ubuntu-latest
          #   python-version: '3.10'
          - os: macos-latest
            python-version: 3.9
          - os: windows-latest
            python-version: 3.9

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install OS dependencies
      shell: bash -l {0}
      run: |
          case "${{ runner.os }}" in
          Linux)
            sudo apt-get install -yy  libsamplerate0 libsndfile1
            ;;
          macOS)
            brew install libsamplerate
            ;;
          esac
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch
        pip install -e ".[test,lint]"
    - name: Lint with pysen
      run: |
        pysen run lint
    - name: Test
      run: |
        nosetests --with-coverage --cover-package=nnmnkwii -v -w tests/ -a '!require_local_data,!modspec'
